version: '3'

services:
    checkers-webui:
        container_name: checkers-webui
        image: ghcr.io/ro99bre/checkers-sa/checkers-webui:latest

        ports:
          - "80:80"

        networks:
            - checkers

        restart: unless-stopped

    checkers-core:
        container_name: checkers-core
        image: ghcr.io/ro99bre/checkers-sa/checkers-core:latest

        networks:
            - checkers

        restart: unless-stopped

    checkers-storage:
        container_name: checkers-storage
        image: ghcr.io/ro99bre/checkers-sa/checkers-storage:latest

        networks:
            - checkers

        restart: unless-stopped

    checkers-db:
        container_name: checkers-db
        image: postgres:14

        networks:
            - checkers

        environment:
            - POSTGRES_USER=checkers
            - POSTGRES_PASSWORD=checkers@postgresql
            - POSTGREA_DB=checkers

        restart: unless-stopped


networks:
    checkers:

