version: '3'

services:
    checkers-webui:
        container_name: checkers-webui
        image: checkers-webui:latest

        ports:
          - "80:80"

        networks:
            - checkers

        restart: unless-stopped

    checkers-core:
        container_name: checkers-core
        image: checkers-core:latest

        networks:
            - checkers

        restart: unless-stopped

    checkers-storage:
        container_name: checkers-storage
        image: checkers-storage:latest

        networks:
            - checkers

        restart: unless-stopped


networks:
    checkers:

