name: Checkers Build and Test

on: [push]

jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Code for Base Application
      run: sbt compile

    - name: Build Code for Storage Manager
      run: sbt storage/compile

    - name: Build Code for TextUI
      run: sbt textui/compile

    - name: Run tests for Base Application
      run: sbt test

    # - name: Run tests for Storage Manager
    #   run: sbt storage/test

    - name: Run tests for TextUI
      run: sbt textui/test

    # - name: Upload coverage data to Coveralls
    #   run: sbt coverageReport coveralls
    #   env:
    #     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}

  docker_Checkers:
    runs-on: ubuntu-latest
    needs: compile_and_test
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Artifact for Base Application
      run: sbt assembly

    - name: Build Docker Image for Base Application
      run: docker build .

  docker_StorageManager:
    runs-on: ubuntu-latest
    needs: compile_and_test
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Artifact for Base Application
      run: sbt storage/assembly

    - name: Build Docker Image for Base Application
      run: docker build StorageManager/
